language: java
jdk:
- oraclejdk8
script:
- ./gradlew test
- ./gradlew -Pversion=$TRAVIS_TAG assembleDist
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy: 
- "echo ------"
- "echo '$TRAVIS_TAG'"
- "echo '$TRAVIS_BUILD_DIR'"
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: $DEPLOY_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/build/distributions/jasome-$TRAVIS_TAG.zip"
    - "$TRAVIS_BUILD_DIR/build/distributions/jasome-$TRAVIS_TAG.tar"
  skip_cleanup: true
  on:
    repo: rodhilton/jasome
    tags: true