# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jira
        pip install gitpython
    #- name: checkout remote
      #uses: actions/checkout@master
      #with:
        #repository: ${{github.event.issue.body}}
        #path: ${{github.event.issue.title}}

    - name: get_issue_details
      if: contains(github.event.issue.labels.*.name, 'New_Project')
      run: python issue.py ${{github.event.issue.title}} > issue_name.txt

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.event.issue.title}}
        path: issue_name.txt

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: issue_name.txt
        asset_name: ${{github.event.issue.title}}
        tag: ${{ github.ref }}
        overwrite: true

    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
          The new projects data can be found at releases

